---
  - name: Conditional Playbook 
    hosts: all
    become: true
    become_method: sudo

    tasks:
    - name: Install Package
      package: 
       name: telnet
       state: present
    
    
    - name: Information
      ansible.builtin.debug: 
        var: ansible_facts ['distribution']   
        

      
        
