--- #ansible-playbook -i /tmp/inventory file.yaml 
- name: Example Playbook
  hosts: ubuntu
  user: ubuntu
  become: true
  become_method: sudo


  tasks:
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /etc/foo.conf
      owner: ec2-user
      group: ec2-user
      mode: '0644'  
      state: touch
...

