--- # ansible-playbook -i /tmp/inventory geturl.yaml 
- name: Example Playbook
  hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Download wordpress
    ignore_errors: true
    ansible.builtin.get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz
        mode: '0440'

  - name: Unzip wordpress
    ignore_errors: true
    ansible.builtin.unarchive:
        src: /tmp/latest.tar.gz
        dest: /tmp
        remote_src: true
