--- # ansible-playbook -i /tmp/inventory lineinfile.yaml 
- name: ExamLineinfile Playbook
  hosts: amazon
  user: ubuntu
  become: true
  become_method: sudo
  
  tasks:
   - name: Add a line to a file if the file does not exist, without passing regexp
     ansible.builtin.lineinfile:
        path: /tmp/testfile
        line: 192.168.1.99 foo.lab.net foo
        create: yes
...

