- name: Example Playbook
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Information
      ansible.builtin.debug:
        var: 'ansible_facts[''distribution_version'']'
  
    - name: Add  users to Amazon
      when:
        - 'ansible_facts[''distribution''] == "Amazon"'
      ansible.builtin.user:
        name: '{{ item }}'
        generate_ssh_key: 'yes'
        ssh_key_file: .ssh/id_rsa
      with_items:
        - Bob
        - Ben
        - Lisa
        - Katty
  
    - name: Download a csv file
      when:
        - 'ansible_facts[''distribution''] == "Amazon"'
      ignore_errors: true
      ansible.builtin.get_url:
        url: 'https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv'
        dest: /home
        mode: '777'

    - name: Copy file with owner and permissions
      when:
        - 'ansible_facts[''distribution''] == "Amazon"'
      ansible.builtin.copy:
        src: /home/addresses.csv
        dest: /home/{{ item }}
        remote_src: yes
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0644'
      with_items:
        - Bob
        - Ben
        - Lisa
        - Katty  
