--- #ansible-playbook -i /tmp/inventory update.yaml 
- name: Update Playbook
  hosts: all
  become: true
  become_method: sudo
  
  tasks:
    - name: Update packages
      ansible.builtin.package:
        name:  "*"
        state: latest
...

