--- #ansible-playbook -i /tmp/inventory user.yaml 
- name: User Playbook
  hosts: all
  become: true
  become_method: sudo


  tasks:
    - name: Add the user 'johnd' 
      ansible.builtin.user:
        name: johnd
        comment: John Doe
        
...

