--- #ansible-playbook -i /tmp/inventory userwithloop.yaml 
- name: User Playbook
  hosts: all
  become: true
  become_method: sudo


  tasks:
    - name: Add the user 'johnd' 
      ansible.builtin.user:
        name: "{{ item }}"
      with_items:
      - john
      - ben
      - lisa
      - mert

    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      with_items: # loop for many items
      - sales2
      - marketing
      - billing
      - IT
...

