--- # ansible-playbook -i /tmp/inventory zip.yaml 
- name: zipping Playbook
  hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: zipping files over 90 days
    raw: 'find /var/log -type f -name "*.log" -mtime +90 -exec gzip -v9 {} +' 
  - name: zipping files over 100M
    raw: 'find /var/log -type f -name "*.log" -size +100M -exec gzip -v9 {} +' 
...