---
# handlers file for wordpress
- name: Start Webserver
  when: 
  - ansible_facts['distribution'] == "Amazon"
  - ansible_facts['distribution_version'] == "2"
  systemd: 
    name: "{{ item }}" 
    state: restarted
    enabled: true
  with_items:
  - httpd
  - crond
